from pydantic.dataclasses import dataclass, Field as field
from typing import Optional

# import xray_config.app.dispatcher as dispatcher
# import xray_config.app.proxyman.inbound as inbound
# import xray_config.app.proxyman.outbound as outbound
# import xray_config.app.commander as commander
# import xray_config.app.log.command as command
# import xray_config.app.proxyman.command as command
# import xray_config.app.stats.command as command
# import xray_config.app.observatory.command as command
# import xray_config.app.dns as dns
# import xray_config.app.dns.fakedns as fakedns
# import xray_config.app.log as log
# import xray_config.app.metrics as metrics
# import xray_config.app.policy as policy
# import xray_config.app.reverse as reverse
# import xray_config.app.router as router
# import xray_config.app.stats as stats
# import xray_config.transport.internet.tagged.taggedimpl as taggedimpl
# import xray_config.app.observatory as observatory
# import xray_config.proxy.blackhole as blackhole
# import xray_config.proxy.dns as dns
# import xray_config.proxy.dokodemo as dokodemo
# import xray_config.proxy.freedom as freedom
# import xray_config.proxy.http as http
# import xray_config.proxy.loopback as loopback
# import xray_config.proxy.shadowsocks as shadowsocks
# import xray_config.proxy.socks as socks
# import xray_config.proxy.trojan as trojan
# import xray_config.proxy.vless.inbound as inbound
# import xray_config.proxy.vless.outbound as outbound
# import xray_config.proxy.vmess.inbound as inbound
# import xray_config.proxy.vmess.outbound as outbound
# import xray_config.proxy.wireguard as wireguard
# import xray_config.transport.internet.domainsocket as domainsocket
# import xray_config.transport.internet.grpc as grpc
# import xray_config.transport.internet.http as http
# import xray_config.transport.internet.httpupgrade as httpupgrade
# import xray_config.transport.internet.kcp as kcp
# import xray_config.transport.internet.quic as quic
# import xray_config.transport.internet.reality as reality
# import xray_config.transport.internet.splithttp as splithttp
# import xray_config.transport.internet.tcp as tcp
# import xray_config.transport.internet.tls as tls
# import xray_config.transport.internet.udp as udp
# import xray_config.transport.internet.websocket as websocket
# import xray_config.transport.internet.headers.http as http
# import xray_config.transport.internet.headers.noop as noop
# import xray_config.transport.internet.headers.srtp as srtp
# import xray_config.transport.internet.headers.tls as tls
# import xray_config.transport.internet.headers.utp as utp
# import xray_config.transport.internet.headers.wechat as wechat
# import xray_config.transport.internet.headers.wireguard as wireguard
# import xray_config.main.json as json
# import xray_config.main.toml as toml
# import xray_config.main.yaml as yaml
# import xray_config.main.confloader.external as external
# import xray_config.main.commands.all as all
